# Generated by Django 4.0.4 on 2022-05-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vollclub', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
